const icons={

Logo:require('./images/FXmaster.png'),
payment:require('./images/payment.png'),
LogoBlue:require('./images/FXmasterBlue.png'),
LogoBlack:require('./images/FrameBlack.png'),
payments:require('./images/Payments.png'),
personal:require('./images/personal.png'),
frame1:require('./images/Frame1.png'),
country:require('./images/country.png'),
sender:require('./images/sender.png'),
wokring:require('./images/working.png'),
paper:require('./images/paper.png'),
group:require('./images/Group.png'),
appDownload:require('./images/appDownLoad.png'),
roundedCirlce:require('./images/rounderCircle.png'),
fx:require('./images/fx.png'),
playstore:require('./images/playstore.png'),
appstore:require('./images/appstore.png'),
camera:require('./images/camera.png'),
purse:require('./images/purse.png'),
icon1:require('./images/icon1.png'),
badge:require('./images/badge.png'),
imageBadge:require('./images/imageBadge.png'),
// verticalcard:require('./images/verticalcard.png'),
// country icon

uk:require('./images/uk.png'),
australia:require('./images/Australia.png'),
turkey:require('./images/Turkey.png'),
europe:require('./images/Europe.png'),
china:require('./images/china.png'),
hungrey:require('./images/Hungary.png'),
newzeland:require('./images/NewZealand.png'),
romania:require('./images/Romania.png'),
canada:require('./images/Canada.png'),
singapore:require('./images/Singapore.png'),
twitter:require('./images/twitter.png'),
linkedin:require('./images/linkedin.png'),
greater:require('./images/greter.png'),


// help icon

icon8:require('./images/icon8.png'),
icon2:require('./images/icon2.png'),
icon3:require('./images/icon3.png'),
icon4:require('./images/icon4.png'),
icon5:require('./images/icon5.png'),
icon6:require('./images/icon6.png'),
// icon7:require('./images/icon7.png'),
fxx:require('./images/FXX.png'),
google:require('./images/googlr.png'),
dk:require('./images/dk.jpg'),
mobile:require('./images/mobile.png'),
blog:require('./images/blog.png'),
computer:require('./images/computer.png'),

auth:require('./images/auth.png'),
ip:require('./images/ip.png'),
people:require('./images/people.png'),
security:require('./images/security.png'),
friend:require('./images/friend.png'),
girls:require('./images/girls.png'),
money:require('./images/money.png'),
tick:require('./images/tick.png'),
graph:require('./images/graph.png'),
search:require('./images/search.png'),
secure:require('./images/secure.png'),
stark:require('./images/stark.png'),
man:require('./images/man.png'),
mic:require('./images/mic.png'),
action:require('./images/action.png'),
close:require('./images/close.png'),
globe:require('./images/globe.png'),
women:require('./images/women.png'),
blackrock:require('./images/blackrock.png'),
blackkey:require('./images/blackkey.png'),
blacksecure:require('./images/blacksecure.png'),
globemap:require('./images/globemap.png'),
itemsWrapper:require('./images/itemsWrapper.png'),
process:require('./images/process.png'),
instruments:require('./images/instruments.png'),
building:require('./images/building.png'),
handshake:require('./images/handshake.png'),
ladies:require('./images/ladies.png'),
netwokring:require('./images/networking.png'),
yellowrounder:require('./images/yellowrounder.png'),
america:require('./images/america.png'),
london:require('./images/london.png'),
sbi:require('./images/sbi.png'),
starlink:require('./images/starlink.png'),
slice:require('./images/slice.png'),
manwith:require('./images/manwith.png'),
certificate:require('./images/certificate.png'),
dk1:require('./images/3k.png'),
student:require('./images/student.png'),
gateway:require('./images/gateway.png'),
testi:require('./images/testi.png'),
groupgirl:require('./images/groupgirl.png'),
outlineacc:require('./images/outlineacc.png'),
man1:require('./images/man1.png'),
man2:require('./images/man2.png'),
man3:require('./images/man3.png'),
mobileViews:require('./images/mobileview.png'),
cirlceView:require('./images/CircleView.jpg'),
ladiesstudy:require('./images/ladiestudy.png')      
}
export default icons;